stages:
  - init
  - workflows

before_script:
  - export PATH="$CI_PROJECT_DIR/miniconda/bin:$PATH"

initialize-conda:
  stage: "init"
  image: "ubuntu:latest"
  script: "bash .circleci/setup.sh"
  cache:
    key: "v1"
    paths:
      - "$CI_PROJECT_DIR/miniconda/"

run-chipseq:
  stage: "workflows"
  image: "ubuntu:latest"
  script:
    - echo $PATH
    - which conda
    - source activate lcdb-wf-test
    - python ci/get-data.py
    - cd workflows/chipseq
    - ./run_test.sh -n
  cache:
    key: "v1"
    paths:
      - "$CI_PROJECT_DIR/miniconda/"
    policy: "pull"
