stages:
  - init
  - workflows

before_script:
  - export PATH="$CI_PROJECT_DIR/miniconda/bin:$PATH"

initialize-conda:
  stage: "init"
  image: "ubuntu:latest"
  script:
    - "bash .circleci/setup.sh"
    - "conda env export -n lcdb-wf-test > env.yaml"
  cache:
    key: "v1"
    paths:
      - "$CI_PROJECT_DIR/miniconda/"
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/env.yaml'


run-chipseq:
  stage: "workflows"
  image: "ubuntu:latest"
  script:
    - source activate lcdb-wf-test
    - python ci/get-data.py
    - cd workflows/chipseq
    - ./run_test.sh --use-conda -j8 -k -p -r
  cache:
    key: "v1"
    paths:
      - "$CI_PROJECT_DIR/miniconda/"
    policy: "pull"
