version: 2

variables:

  defaults: &defaults
    docker:
      - image: bioconda/bioconda-utils-build-env

  restore_cache: &restore_cache
    restore_cache:
      keys:
        - v1-{{ checksum "requirements.txt" }}

  save_cache: &save_cache
    save_cache:
      key: v1-{{ checksum "requirements.txt" }}
      paths:
        - miniconda

  setup: &setup
    run: 
      name: Setup conda
      command: .circleci/setup.sh

  get-data: &get-data
    run:
      name: Download example data
      command: python ci/get-data.py

  setup-ssh: &setup-ssh
    run:
      name: Setup ssh
      command: |
        mkdir -p ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  setup-base: &setup-base
    run: 
      name: Setup base system
      command: |
        cat >> $BASH_ENV <<EOF
        if [[ \$- == *u* ]] ; then
            set +u ; . /tmp/repo/docker-entrypoint-source ; set -u
        else
            . /tmp/repo/docker-entrypoint-source
        fi
        EOF

  chipseq-step: &chipseq-step
      run:
        name: chipseq workflow
        command: |
          cd workflows/chipseq
          source activate lcdb-wf-test
          snakemake --configfile config/config.yaml --use-conda -j2 -T -k -p -r

  references-step: &references-step
      run:
        name: references workflow
        command: |
          cd workflows/references
          source activate lcdb-wf-test
          snakemake --configfile config/config.yaml --use-conda -j2 -T -k -p -r

  rnaseq-step: &rnaseq-step
      run:
        name: rnaseq workflow
        command: |
          cd workflows/rnaseq
          source activate lcdb-wf-test
          snakemake --configfile config/config.yaml --use-conda -j2 -T -k -p -r

jobs:

  initial-setup:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *setup
      - *save_cache

  chipseq:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - *restore_cache
      - *get-data
      - *chipseq-step

  rnaseq:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - *restore_cache
      - *setup
      - *save_cache
      - *get-data
      - *rnaseq-step

  references:
    <<: *defaults
    parallelism: 2
    steps:
      - checkout
      - *restore_cache
      - *setup
      - *save_cache
      - *get-data
      - *references-step

workflows:
  version: 2
  test-suite:
    jobs:
      - initial-setup
      - chipseq:
          requires:
            - initial-setup
          filters:
            branches:
              ignore:
                - master
      - rnaseq:
          requires:
            - initial-setup
          filters:
            branches:
              ignore:
                - master
      - references:
          requires:
            - initial-setup
          filters:
            branches:
              ignore:
                - master
