sampletable: 'config/sampletable.tsv'

# Which key in the `references` dict below to use
assembly: 'dmel'

# If not specified here, use the environment variable REFERENCES_DIR.
references_dir: 'references_data'

aligner:
  index: 'hisat2'
  tag: 'test'

rrna:
  index: 'bowtie2'
  tag: 'rRNA'

gtf:
  tag: "test"

salmon:
  tag: "test_transcriptome"

merged_bigwigs:
  control_sense:
    sense:
      - sample1
      - sample2
  treatment_all:
    sense:
      - sample3
      - sample4
    antisense:
      - sample3
      - sample4

# See the reference config files in the top level of the repo,
# include/reference_configs. Either paste the contents of one or more of those
# files here, (excluding the "references:" line of each file, so that it
# doesn't overwrite this key) or call Snakemake with the --configfile argument
# for each additional references file you want to include.
references: {}
