sampletable: 'config/sampletable.tsv'

# Which key in the `references` dict below to use
organism: 'dmel'

# If not specified here, use the environment variable REFERENCES_DIR.
references_dir: 'references_data'

aligner:
  index: 'hisat2'
  tag: 'test'

rrna:
  index: 'bowtie2'
  tag: 'rRNA'

gtf:
  tag: "test"

salmon:
  tag: "test_transcriptome"

fastq_screen:
  - label: rRNA
    organism: dmel
    tag: test
  - label: PhiX
    organism: phix
    tag: default
  - label: Fly
    organism: dmel
    tag: test

merged_bigwigs:
  control_sense:
    sense:
      - sample1
      - sample2
  treatment_all:
    sense:
      - sample3
      - sample4
    antisense:
      - sample3
      - sample4

# See the reference config files in the top level of the repo,
# include/reference_configs, for inspiration for more species.
references:
  dmel:
    test:
      fasta:
        url: "https://raw.githubusercontent.com/lcdb/lcdb-test-data/master/data/seq/dm6.small.fa"
        postprocess: 'lib.common.gzipped'
        indexes:
          - 'bowtie2'
          - 'hisat2'
      gtf:
        url: "https://raw.githubusercontent.com/lcdb/lcdb-test-data/master/data/annotation/dm6.small.gtf"
        postprocess: 'lib.common.gzipped'
        conversions:
          - 'refflat'
          - gffutils: # kwargs below will be provided to `gffutils.create_db`
              merge_strategy: 'merge'
              id_spec:
                  transcript: ['transcript_id', 'transcript_symbol']
                  gene: ['gene_id', 'gene_symbol']
              gtf_transcript_key: 'transcript_id'
              gtf_gene_key: 'gene_id'

          # the attribute from the GTF to consider gene ID
          - genelist:
              gene_id: 'gene_id'

          # a <- AnnotationHub()
          # a[(a$rdataclass == 'OrgDb') & grepl('melanogaster', a$species),]
          - annotation_hub:
              ahkey: 'AH57972'
              keytype: 'ENSEMBL'

    test_transcriptome:
      fasta:
        url: "https://raw.githubusercontent.com/lcdb/lcdb-test-data/master/data/seq/dm6.small.transcriptome.fa"
        postprocess: 'lib.common.gzipped'
        indexes:
          - 'salmon'

include_references:
  - '../../include/reference_configs/PhiX.yaml'
  - '../../include/reference_configs/Drosophila_melanogaster.yaml'
