# ============================================================================
# RNA-seq configuration file
# ============================================================================
#
# The rnsaeq.Rmd RMarkdown file reads in the values from this YAML file.
#
# This file is split into sections, indicated by the top-level keys. RMarkdown
# chunks may depend on one or more of these sections. Changing a value in
# a section will therefore cause all chunks depending on that section to be
# re-run.

main:

  # Path to sample table. It can be modified in the colData chunk if needed.
  sampletable: "../config/sampletable.tsv"


  # If you are using Ensembl annotations with gene IDs like ENSG000001.1 (with
  # the dotted version number), then these genes will not be found in the
  # OrgDb. Set this to TRUE to strip off the dotted version to fix this.
  strip_dotted_version: TRUE

  # If you have technical replicates, you can automatically collapse them.
  # Provide a column in colData here, and for each unique value in the column
  # the counts across samples sharing that value will be summed. Typically this
  # would be set to the column representing biological replicate.
  collapse_by: NULL

  lfc_thresh: 0

  # By default DESeq2 assumes alpha of 0.1 (when filtering low-count genes). If
  # you want something else, change it here.
  alpha: 0.1


plotting:
  # For each item in this list you will get columns of colors in the clustered
  # heatmap and tabs for PCA plots.
  covariates_for_plots:
    - group

  # These arguments are passed to the clusterProfiler plotting functions. Any
  # arguments accepted by those functions can be added here.
  dotplot_args:
    showCategory: 20
    color: p.adjust
    x: GeneRatio

  emapplot_args:
    showCategory: 35
    color: p.adjust

  cnetplot_args:
    showCategory: 5
    foldChange: NULL
    colorEdge: FALSE
    circular: FALSE
    node_label: all

# Parallel configuration
parallel:

  parallel: FALSE
  # If integer, use that many cores. If string, assume it's the name of an
  # environment variable that stores the number of cores (e.g.,
  # "SLURM_CPUS_PER_TASK")
  cores: 8

# This section provides toggles for various parts of the analysis.
toggle:

  # Import Salmon results instead of featureCounts?
  salmon: FALSE

  # Import Kallisto results instead of featureCounts?
  kallisto: FALSE

  # Run functional enrichment analysis?
  functional_enrichment: FALSE

  # If functional_enrichment is TRUE, you can optionally disable Reactome here
  # if noReactome database exists for your organism or the package is not
  # installed.
  run_reactome: FALSE

  # Run gene patterns analysis?
  gene_patterns: FALSE

  # Include help docs at the end of the HTML?
  help_docs: TRUE

# This section configures annotations and databases.
orgdb:

  # Specify the genus and species
  annotation_genus_species: "Drosophila melanogaster"

  # You can optionally provide a specific key for AnnotationHub which will
  # override the annotation_genus_species. Use this if you have a specific
  # older OrgDb to use.
  annotation_key_override: NULL

  # The OrgDb will be downloaded here and subsequently read directly from this
  # directory
  hub_cache: "../../../include/AnnotationHubCache"

  # OrgDb key indicating the format of gene IDs in rownames(dds).
  keytype: 'ENSEMBL'

  # Additional columns from the OrgDb to attach to the results
  orgdb_columns:
    - SYMBOL
    - ALIAS
    - UNIPROT

  # For each column listed here, if a value is NA then it will be filled in
  # with the corresponding value from keytype above. Useful for when you want
  # use symbol where possible but fill in with the Ensembl ID when symbol is
  # not available.
  fill:
    - SYMBOL

  # Which column to use when labeling plots? E.g., MA and volcano plots
  label_column: SYMBOL


# This section configures the functional enrichment.
functional_enrichment:

  # Organism code for KEGG
  kegg_organism: dme

  # Organism code for Reactome
  reactome_organism: fly

  # What is the OrgDb key type used for Gene Ontology?
  go_keytype: ENTREZID

  # What is the OrgDb key type used for KEGG?
  kegg_keytype: ncbi-geneid

  # Any GO terms above these cutoffs will not be reported. Set to 1 if you're
  # fine getting plots even with no statistically significant terms.
  pvalueCutoff: 1
  qvalueCutoff: 1

  # For KEGG, the object returned might need to be converted
  id_convert: TRUE

  # Universe used for GO and pathway enrichment. NULL means all genes.
  go_uni: NULL
  path_uni: NULL
